#!/usr/bin/env python3
"""
Reads the CoffeeScript frequency_lists.coffee and outputs a Swift source file.
Uses comma-separated strings (split at runtime) to avoid huge array literal compile times.
"""

import re
import os

def parse_frequency_lists(coffee_path):
    with open(coffee_path, 'r') as f:
        content = f.read()

    pattern = r'^\s+(\w+):\s+"([^"]+)"'
    dicts = {}
    for match in re.finditer(pattern, content, re.MULTILINE):
        name = match.group(1)
        words_str = match.group(2)
        dicts[name] = words_str
    return dicts

def generate_swift(dicts, output_path):
    lines = []
    lines.append('// Generated by generate_frequency_lists.py — do not edit manually')
    lines.append('')
    lines.append('enum FrequencyLists {')

    for name, words_str in dicts.items():
        # Escape any backslashes or quotes in the string
        escaped = words_str.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'    private static let {name}Raw = "{escaped}"')
    lines.append('')

    lines.append('    private static let rawData: [String: String] = [')
    for name in dicts:
        lines.append(f'        "{name}": {name}Raw,')
    lines.append('    ]')
    lines.append('')
    lines.append('    private static var _rankedDictionaries: [String: [String: Int]]?')
    lines.append('')
    lines.append('    static var rankedDictionaries: [String: [String: Int]] {')
    lines.append('        if let cached = _rankedDictionaries { return cached }')
    lines.append('        var result: [String: [String: Int]] = [:]')
    lines.append('        for (name, raw) in rawData {')
    lines.append('            var ranked: [String: Int] = [:]')
    lines.append('            var rank = 1')
    lines.append('            for word in raw.split(separator: ",") {')
    lines.append('                ranked[String(word)] = rank')
    lines.append('                rank += 1')
    lines.append('            }')
    lines.append('            result[name] = ranked')
    lines.append('        }')
    lines.append('        _rankedDictionaries = result')
    lines.append('        return result')
    lines.append('    }')
    lines.append('')
    lines.append('    static func setUserInputDictionary(_ orderedList: [String]) {')
    lines.append('        var ranked: [String: Int] = [:]')
    lines.append('        for (index, word) in orderedList.enumerated() {')
    lines.append('            ranked[word] = index + 1')
    lines.append('        }')
    lines.append('        if _rankedDictionaries == nil {')
    lines.append('            _ = rankedDictionaries')
    lines.append('        }')
    lines.append('        _rankedDictionaries?["user_inputs"] = ranked')
    lines.append('    }')
    lines.append('}')
    lines.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    coffee_path = os.path.join(script_dir, '..', '..', 'src', 'frequency_lists.coffee')
    output_path = os.path.join(script_dir, '..', 'Sources', 'Zxcvbn', 'Data', 'FrequencyLists.swift')

    dicts = parse_frequency_lists(coffee_path)
    generate_swift(dicts, output_path)
    total = sum(len(v.split(',')) for v in dicts.values())
    print(f'Generated FrequencyLists.swift with {len(dicts)} dictionaries, {total} total words')
