#!/usr/bin/env python3
"""
Reads the CoffeeScript adjacency_graphs.coffee and outputs a Swift source file.
Uses a compact string format parsed at runtime to avoid slow dictionary literal compilation.

Format: "key\tadj1\x00adj2\x00...\n" where empty adjacents use empty string.
"""

import json
import re
import os

def extract_json_object(content, start):
    assert content[start] == '{'
    depth = 0
    in_string = False
    escape = False
    i = start
    while i < len(content):
        c = content[i]
        if escape:
            escape = False
            i += 1
            continue
        if c == '\\' and in_string:
            escape = True
            i += 1
            continue
        if c == '"':
            in_string = not in_string
        elif not in_string:
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    return content[start:i+1]
        i += 1
    return None

def parse_adjacency_graphs(coffee_path):
    with open(coffee_path, 'r') as f:
        content = f.read()

    graphs = {}
    for match in re.finditer(r'(\w+):\s*\{', content):
        name = match.group(1)
        if name in ('adjacency_graphs', 'module'):
            continue
        obj_start = match.start(0) + len(match.group(0)) - 1
        json_str = extract_json_object(content, obj_start)
        if json_str:
            graph = json.loads(json_str)
            graphs[name] = graph
    return graphs

def encode_graph(graph):
    """Encode graph as a compact string.
    Each key is on its own line: key<TAB>adj1<NUL>adj2<NUL>...
    Null adjacents are encoded as empty string between NULs.
    """
    lines = []
    for key in sorted(graph.keys()):
        adjacents = graph[key]
        adj_strs = []
        for a in adjacents:
            adj_strs.append(a if a is not None else "")
        lines.append(key + "\t" + "\0".join(adj_strs))
    return "\n".join(lines)

def swift_string_literal(s):
    """Convert a string to a Swift string literal, escaping special chars."""
    result = []
    for c in s:
        if c == '\\':
            result.append('\\\\')
        elif c == '"':
            result.append('\\"')
        elif c == '\n':
            result.append('\\n')
        elif c == '\t':
            result.append('\\t')
        elif c == '\0':
            result.append('\\0')
        else:
            result.append(c)
    return '"' + ''.join(result) + '"'

def generate_swift(graphs, output_path):
    lines = []
    lines.append('// Generated by generate_adjacency_graphs.py — do not edit manually')
    lines.append('')
    lines.append('enum AdjacencyGraphs {')
    lines.append('    private static func parseGraph(_ raw: String) -> [String: [String?]] {')
    lines.append('        var result: [String: [String?]] = [:]')
    lines.append('        for line in raw.split(separator: "\\n", omittingEmptySubsequences: false) {')
    lines.append('            let parts = line.split(separator: "\\t", maxSplits: 1, omittingEmptySubsequences: false)')
    lines.append('            guard parts.count == 2 else { continue }')
    lines.append('            let key = String(parts[0])')
    lines.append('            let adjacents = parts[1].split(separator: "\\0", omittingEmptySubsequences: false).map { adj -> String? in')
    lines.append('                let s = String(adj)')
    lines.append('                return s.isEmpty ? nil : s')
    lines.append('            }')
    lines.append('            result[key] = adjacents')
    lines.append('        }')
    lines.append('        return result')
    lines.append('    }')
    lines.append('')

    for name, graph in graphs.items():
        encoded = encode_graph(graph)
        swift_str = swift_string_literal(encoded)
        lines.append(f'    private static let {name}Raw = {swift_str}')
    lines.append('')

    for name in graphs:
        lines.append(f'    static let {name}: [String: [String?]] = parseGraph({name}Raw)')
    lines.append('')

    lines.append('    static let allGraphs: [String: [String: [String?]]] = [')
    for name in graphs:
        lines.append(f'        "{name}": {name},')
    lines.append('    ]')
    lines.append('}')
    lines.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    coffee_path = os.path.join(script_dir, '..', '..', 'src', 'adjacency_graphs.coffee')
    output_path = os.path.join(script_dir, '..', 'Sources', 'Zxcvbn', 'Data', 'AdjacencyGraphs.swift')

    graphs = parse_adjacency_graphs(coffee_path)
    generate_swift(graphs, output_path)
    print(f'Generated AdjacencyGraphs.swift with {len(graphs)} graphs')
    for name, graph in graphs.items():
        print(f'  {name}: {len(graph)} keys')
